development:
  adapter: postgresql
  database: wh40k_datasheet_generator_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: wh40k_datasheet_generator_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: wh40k_datasheet_generator_production
  pool: 5
  timeout: 5000